apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "dali-%s-pvc" (include "hpcc-efs.fullname" $) }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.daliStorage.size }}
  storageClassName: {{ printf "dali-%s-sc" (include "hpcc-efs.fullname" $) }}
