apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "data-%s-pvc" (include "hpcc-efs.fullname" $) }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.dataStorage.size }}
  storageClassName: {{ printf "data-%s-sc" (include "hpcc-efs.fullname" $) }}
