apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ printf "dll-%s-pvc" (include "hpcc-efs.fullname" $) }}
spec:
  accessModes:
    - ReadWriteMany  # accessed from dali and sasha
  resources:
    requests:
      storage: {{ .Values.dllStorage.size }}
  storageClassName: {{ printf "dll-%s-sc" (include "hpcc-efs.fullname" $) }}
